#! /usr/bin/python
##
# *BURP* HTML Analyzer
# Prints an analysis of the given URL in JSON format
# Usage: burp-html [URL]
##

import os, sys, json

from burphtml.analyzer import HTMLAnalyzer

try:
  from urllib.request import URLError
except ImportError:
  from urllib2 import URLError

if not len(sys.argv) == 2:
  print("Usage: " + sys.argv[0] + " [URL]")
  exit(1)

url = sys.argv[1]

try:
  analysis = HTMLAnalyzer(url).analyze()
except URLError:
  print("Error: Invalid URL")
  exit(1)

print( json.dumps(analysis) )

